name: Release web app

on:
  workflow_dispatch:
  release:
    types: [ released ]

jobs:
  deployment:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Fetch version from tag
        uses: xom9ikk/version-by-tag@v1
        id: version_by_tag
        with:
          tagName: ${{ github.ref_name }}
          isUseGithubRunNumber: true

      - name: Update the .env.release file
        run: |
          echo "VERSION=${{ steps.version_by_tag.outputs.semver }}" > .env.release
          echo "VERSION_CODE=${{ steps.version_by_tag.outputs.versionCode }}" >> .env.release
          echo "COMMIT_SHA=${{ github.sha }}" >> .env.release

      - name: Checkout release branch
        uses: actions/checkout@v2
        with:
          ref: release

      - name: Merge changes from main to release branch
        run: |
          git merge --no-ff --no-commit origin/main

      - name: Push changes to release branch
        run: |
          git push origin release