name: Release web app

on:
  workflow_dispatch:
  release:
    types: [ released ]

jobs:
  deployment:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # Let's get all the branches, otherwise, you will fail to

      - name: Update the env file
        run: |
          echo "VERSION=${{ github.ref_name }}" > .env.release
          echo "COMMIT_SHA=${{ github.sha }}" >> .env.release

      - name: Commit and push changes
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Update the env file via GitHub Actions'
          branch: 'main'
          force: true

      - name: Merge changes from main to release branch
        uses: devvspaces/merge-branches@v1
        with:
          token: ${{ github.token }}
          from_branch: main
          to_branch: release