name: Release web app

on:
  workflow_dispatch:
  release:
    types: [ released ]

jobs:
  deployment:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch version from tag
        uses: xom9ikk/version-by-tag@v1
        id: version_by_tag
        with:
          tagName: ${{ github.ref_name }}
          isUseGithubRunNumber: true

      - name: Update the .env.release file
        run: |
          echo "VERSION=${{ steps.version_by_tag.outputs.semver }}" > .env.release
          echo "VERSION_CODE=${{ steps.version_by_tag.outputs.versionCode }}" >> .env.release
          echo "COMMIT_SHA=${{ github.sha }}" >> .env.release


      - name: Configure GitHub CLI
        run: |
          echo ${{ secrets.PAT }} | gh auth login --with-token
          gh config set prompt disabled

      - name: Commit and push changes to main branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update .env.release file via GitHub Actions"
          gh pr create --title "Update .env.release" --body "Automated PR for updating .env.release file" --base main

      - name: Checkout release branch
        uses: actions/checkout@v2
        with:
          ref: release

      - name: Merge changes from main to release branch
        run: |
          git merge --no-ff --no-commit main

      - name: Push changes to release branch
        run: |
          git push origin HEAD:${{ github.ref }}